# For an overview of all valid add-on configuration options have a look 
# here : https://developers.home-assistant.io/docs/add-ons/configuration/#add-on-configuration
name: "C-Bus CGate to MQTT Server"
description: "Bridge C-Bus to MQTT via a serial interface. Runs three processes: CGate, ser2sock and cgateweb."
version: "0.3.6"
slug: "cbuscgate2mqtt"
init: false
tmpfs: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
usb: true
uart: true
map:
  - share:rw

services:
  - mqtt:need

# ports:
#   1883/tcp: 1883  # Normal MQTT
# I don't understand why, but I get an error that this port is already in use by the host.

host_network: true # Needs to be true, but I don't understand why, if I'm only needing MQTT and the serial port.

options:
  # Serial device path for ser2sock
  serialdevicepath: "/dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0" 
  # cbus project name
  cbusname: "BURS1303"
  # Save CGate events to file.
  useeventfile: false
  # Event level to log to the event file
  eventlevel: 9
  # net and app for automatically requesting values
  getallnetapp: "254/56"
  #  whether to request on start (requires getallnetapp set as well)
  getallonstart: true
  #  how often to request after start (in seconds), (requires getallnetapp set as well)
  getallperiod: 60*60
  #  Sets MQTT retain flag for values coming from cgate
  retainreads: true
  messageinterval: 200
  # cgateweb logging
  logging: 0
schema:
  serialdevicepath: device
  cbusname: str
  useeventfile: bool
  eventlevel: int(0,9)
  getallnetapp: str
  getallonstart: bool
  getallperiod: str
  retainreads: bool
  messageinterval: int
  logging: int(0,9)

codenotary: bdnstn@gmail.com
